- name: Install docker python system packages
  apt:
    name:
      - python3-docker
    state: present
    update_cache: yes
  become: true

- name: Ensure docker is running and enabled
  service:
    name: docker
    state: started
    enabled: yes
  become: true
  tags: traefik  

