---
# handlers file for ansible-traefik
- name: remove traefik container
  docker_container:
    image: "{{ traefik_docker_image }}"
    name: "{{ traefik_container_name }}"
    state: absent

- name: remove traefik docker network
  docker_network:
    name: "{{ traefik_docker_network }}"
    state: absent

- name: create traefik docker network
  docker_network:
    name: "{{ traefik_docker_network }}"
    appends: yes

- name: start traefik through docker compose
  community.docker.docker_compose_v2:
    project_src: "{{ traefik_install_dir }}"
    state: present
    pull: always
    recreate: always

- name: recreate traefik container
  debug:
    msg: "Recreating traefik"
  changed_when: True
  notify:
    - remove traefik container
    - create traefik docker network
    - start traefik through docker compose

- name: remove traefik image
  docker_image:
    path: "{{ traefik_install_dir }}"
    name: "{{ traefik_container_name }}"
    state: absent
